install.packages("devtools")
devtools::install_github("fowlerjk/rsurveygizmo", force = T)
devtools::install_github("leonidliu/liutils")
install.packages("googlesheets4")
install.packages("knitr")
install.packages("margins")
install.packages("broom")
install.packages("mgcv")
install.packages("rmarkdown")
