install.packages("devtools")
library(devtools)
install_github("fowlerjk/rsurveygizmo", force = T)
install_github("leonidliu/liutils")
install.packages("googlesheets4")
install.packages("knitr")
install.packages("margins")
install.packages("broom")
install.packages("mgcv")
